// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using print_attestation.ContextDb;

#nullable disable

namespace print_attestation.Migrations
{
    [DbContext(typeof(askContext))]
    [Migration("20260902084759___0")]
    partial class __0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("print_attestation.Model.t_demande_annulation", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("r_date_traitement")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("r_motif_annulation_id_fk")
                        .HasColumnType("int");

                    b.Property<string>("r_motif_rejet")
                        .HasColumnType("longtext");

                    b.Property<string>("r_num_attestation")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("r_num_immatriculation")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("r_num_police")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("r_site_id_fk")
                        .HasColumnType("int");

                    b.Property<int>("r_status")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.Property<int>("r_user_id_fk")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex("r_created_at");

                    b.HasIndex("r_motif_annulation_id_fk");

                    b.HasIndex("r_site_id_fk");

                    b.HasIndex("r_status");

                    b.HasIndex("r_user_id_fk");

                    b.ToTable("t_demande_annulation");
                });

            modelBuilder.Entity("print_attestation.Model.t_histo_email", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<string>("r_bcc")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("r_body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("r_cc")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_html")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("r_raison_echec")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("r_recipients")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("r_sender_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("r_sender_name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("r_statut")
                        .HasColumnType("int");

                    b.Property<string>("r_subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex(new[] { "r_created_at" }, "IX_HistoEmail_CreatedAt");

                    b.HasIndex(new[] { "r_recipients" }, "IX_HistoEmail_Recipients");

                    b.HasIndex(new[] { "r_statut" }, "IX_HistoEmail_Statut");

                    b.ToTable("t_histo_email");
                });

            modelBuilder.Entity("print_attestation.Model.t_histo_sms", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("r_provider_message_id")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("r_raison_echec")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("r_recipient")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("r_sender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("r_statut")
                        .HasColumnType("int");

                    b.Property<string>("r_text")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("varchar(1600)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex(new[] { "r_created_at" }, "IX_HistoSms_CreatedAt");

                    b.HasIndex(new[] { "r_recipient" }, "IX_HistoSms_Recipient");

                    b.HasIndex(new[] { "r_statut" }, "IX_HistoSms_Statut");

                    b.ToTable("t_histo_sms");
                });

            modelBuilder.Entity("print_attestation.Model.t_job", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<string>("r_attestations")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("r_completed_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<int>("r_errors")
                        .HasColumnType("int");

                    b.Property<string>("r_file_name")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("r_file_path")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("r_job_id")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("r_status")
                        .HasColumnType("int");

                    b.Property<int>("r_success")
                        .HasColumnType("int");

                    b.Property<int>("r_total")
                        .HasColumnType("int");

                    b.Property<string>("r_type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.Property<int>("r_user_id_fk")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex("r_created_at");

                    b.HasIndex("r_job_id");

                    b.HasIndex("r_user_id_fk");

                    b.HasIndex(new[] { "r_job_id" }, "IX_Job_JobId");

                    b.HasIndex(new[] { "r_user_id_fk" }, "IX_Job_UserId");

                    b.ToTable("t_job");
                });

            modelBuilder.Entity("print_attestation.Model.t_job_details", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<string>("r_attestation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<string>("r_desc_error")
                        .HasColumnType("longtext");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("r_job_id_fk")
                        .HasColumnType("int");

                    b.Property<bool?>("r_success")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex("r_created_at");

                    b.HasIndex("r_job_id_fk");

                    b.HasIndex(new[] { "r_job_id_fk" }, "IX_Job_JobIdFk");

                    b.ToTable("t_job_details");
                });

            modelBuilder.Entity("print_attestation.Model.t_modele", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<string>("r_body")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<string>("r_description")
                        .HasColumnType("longtext");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("r_plateforme")
                        .HasColumnType("int");

                    b.Property<string>("r_subject")
                        .HasColumnType("longtext");

                    b.Property<int?>("r_type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.ToTable("t_modele");
                });

            modelBuilder.Entity("print_attestation.Model.t_motif_annulation", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("r_libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex("r_libelle");

                    b.ToTable("t_motif_annulation");
                });

            modelBuilder.Entity("print_attestation.Model.t_refresh_token", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("r_expires_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("r_ip_address")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_revoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("r_jti")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("r_replaced_by")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("r_revoked_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("r_token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.Property<string>("r_user_agent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("r_user_id_fk")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex("r_expires_at", "r_is_delete")
                        .HasDatabaseName("IX_RefreshToken_ExpiresAt_IsDelete");

                    b.HasIndex("r_user_id_fk", "r_is_revoked", "r_expires_at")
                        .HasDatabaseName("IX_RefreshToken_UserId_IsRevoked_ExpiresAt");

                    b.HasIndex(new[] { "r_expires_at" }, "IX_RefreshToken_ExpiresAt");

                    b.HasIndex(new[] { "r_jti" }, "IX_RefreshToken_Jti");

                    b.HasIndex(new[] { "r_token" }, "IX_RefreshToken_Token")
                        .IsUnique();

                    b.HasIndex(new[] { "r_user_id_fk" }, "IX_RefreshToken_UserId");

                    b.ToTable("t_refresh_token");
                });

            modelBuilder.Entity("print_attestation.Model.t_role", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<string>("r_code")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<string>("r_description")
                        .HasColumnType("longtext");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("r_nom")
                        .HasColumnType("longtext");

                    b.Property<int?>("r_ordre")
                        .HasColumnType("int");

                    b.Property<string>("r_sites_types")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.ToTable("t_role");
                });

            modelBuilder.Entity("print_attestation.Model.t_role_scope", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("r_role_id_fk")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("r_scope_code_fk")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex("r_role_id_fk");

                    b.HasIndex("r_scope_code_fk");

                    b.ToTable("t_role_scope");
                });

            modelBuilder.Entity("print_attestation.Model.t_scope", b =>
                {
                    b.Property<string>("r_code")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("r_description")
                        .HasColumnType("longtext");

                    b.Property<string>("r_nom")
                        .HasColumnType("longtext");

                    b.HasKey("r_code");

                    b.ToTable("t_scope");

                    b.HasData(
                        new
                        {
                            r_code = "attestations.read",
                            r_description = "Permet de consulter les attestations",
                            r_nom = "Lecture des attestations"
                        },
                        new
                        {
                            r_code = "attestations.read.all",
                            r_description = "Permet de consulter les attestations de tous les intermediaires",
                            r_nom = "Lecture des attestations de tous les intermediaires"
                        },
                        new
                        {
                            r_code = "demandes-annulations.read",
                            r_description = "Permet de consulter les demandes d'annulation",
                            r_nom = "Lecture des demandes d'annulation"
                        },
                        new
                        {
                            r_code = "demandes-annulations.read.site",
                            r_description = "Permet de consulter les demandes d'annulation de tous les intermediaires",
                            r_nom = "Lecture des demandes d'annulation de mon intérmediaire"
                        },
                        new
                        {
                            r_code = "taches.read",
                            r_description = "Permet de consulter les taches",
                            r_nom = "Lecture des taches"
                        },
                        new
                        {
                            r_code = "taches.read.site",
                            r_description = "Permet de consulter les taches de mon site",
                            r_nom = "Lecture des taches de mon site"
                        },
                        new
                        {
                            r_code = "taches.update",
                            r_description = "Permet d'annuler les taches",
                            r_nom = "Annulation des taches"
                        },
                        new
                        {
                            r_code = "taches.update.site",
                            r_description = "Permet d'annuler les taches de mon site",
                            r_nom = "Annulation des taches de mon site"
                        },
                        new
                        {
                            r_code = "taches.update.all",
                            r_description = "Permet d'annuler les taches de tous les utilisateurs",
                            r_nom = "Annulation des taches de tous les utilisateurs"
                        },
                        new
                        {
                            r_code = "audits.actions.read",
                            r_description = "Permet de consulter les audits liés aux actions",
                            r_nom = "Lecture des audits actions"
                        },
                        new
                        {
                            r_code = "audits.actions.read.site",
                            r_description = "Permet de consulter les audits liés aux actions de mon site",
                            r_nom = "Lecture des audits actions de mon site"
                        },
                        new
                        {
                            r_code = "audits.acces.read",
                            r_description = "Permet de consulter les audits liés aux connexions",
                            r_nom = "Lecture des audits connexions"
                        },
                        new
                        {
                            r_code = "audits.acces.read.site",
                            r_description = "Permet de consulter les audits liés aux connexions de mon site",
                            r_nom = "Lecture des audits connexions de mon site"
                        },
                        new
                        {
                            r_code = "users.read",
                            r_description = "Permet de consulter les utilisateurs",
                            r_nom = "Lecture des utilisateurs"
                        },
                        new
                        {
                            r_code = "sites.create",
                            r_description = "Permet de créer des intermédiaires",
                            r_nom = "Création des intermédiaires"
                        },
                        new
                        {
                            r_code = "sites.update",
                            r_description = "Permet de modifier les intermédiaires",
                            r_nom = "Modification des intermédiaires"
                        },
                        new
                        {
                            r_code = "sites.delete",
                            r_description = "Permet de supprimer les intermédiaires",
                            r_nom = "Suppression des intermédiaires"
                        },
                        new
                        {
                            r_code = "sites.read",
                            r_description = "Permet de consulter les intermédiaires",
                            r_nom = "Lecture des intermédiaires"
                        },
                        new
                        {
                            r_code = "sites.upload",
                            r_description = "Permet de téléverser les intermédiaires",
                            r_nom = "Téléversement des intermédiaires"
                        },
                        new
                        {
                            r_code = "users.create",
                            r_description = "Permet de créer des utilisateurs",
                            r_nom = "Création des utilisateurs"
                        },
                        new
                        {
                            r_code = "users.update",
                            r_description = "Permet de modifier les utilisateurs",
                            r_nom = "Modification des utilisateurs"
                        },
                        new
                        {
                            r_code = "users.delete",
                            r_description = "Permet de supprimer les utilisateurs",
                            r_nom = "Suppression des utilisateurs"
                        },
                        new
                        {
                            r_code = "roles.read",
                            r_description = "Permet de consulter les profils d'utilisateurs",
                            r_nom = "Lecture des profils d'utilisateurs"
                        },
                        new
                        {
                            r_code = "roles.create",
                            r_description = "Permet de créer les profils d'utilisateurs",
                            r_nom = "Création des profils d'utilisateurs"
                        },
                        new
                        {
                            r_code = "roles.update",
                            r_description = "Permet de modifier les profils d'utilisateurs",
                            r_nom = "Modification des profils d'utilisateurs"
                        },
                        new
                        {
                            r_code = "roles.delete",
                            r_description = "Permet de supprimer les profils d'utilisateurs",
                            r_nom = "Suppression des profils d'utilisateurs"
                        },
                        new
                        {
                            r_code = "motifs-annulation.read",
                            r_description = "Permet de consulter les motifs d'annulation",
                            r_nom = "Lecture des motifs d'annulation"
                        },
                        new
                        {
                            r_code = "motifs-annulation.create",
                            r_description = "Permet de créer les motifs d'annulation",
                            r_nom = "Création des motifs d'annulation"
                        },
                        new
                        {
                            r_code = "motifs-annulation.update",
                            r_description = "Permet de modifier les motifs d'annulation",
                            r_nom = "Modification des motifs d'annulation"
                        },
                        new
                        {
                            r_code = "motifs-annulation.delete",
                            r_description = "Permet de supprimer les motifs d'annulation",
                            r_nom = "Suppression des motifs d'annulation"
                        });
                });

            modelBuilder.Entity("print_attestation.Model.t_session", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<string>("r_ip_address")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("r_login_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("r_logout_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("r_token_jti")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.Property<string>("r_user_agent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("r_user_id_fk")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex("r_user_id_fk", "r_is_active", "r_login_at")
                        .HasDatabaseName("IX_Session_UserId_IsActive_LoginAt");

                    b.HasIndex(new[] { "r_is_active" }, "IX_Session_IsActive");

                    b.HasIndex(new[] { "r_login_at" }, "IX_Session_LoginAt");

                    b.HasIndex(new[] { "r_token_jti" }, "IX_Session_TokenJti");

                    b.HasIndex(new[] { "r_user_id_fk" }, "IX_Session_UserId");

                    b.ToTable("t_session");
                });

            modelBuilder.Entity("print_attestation.Model.t_site", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<string>("r_code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("r_nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("r_type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex(new[] { "r_code" }, "IX_Site_Code")
                        .IsUnique();

                    b.HasIndex(new[] { "r_nom" }, "IX_Site_Nom");

                    b.ToTable("t_site");
                });

            modelBuilder.Entity("print_attestation.Model.t_trace_action", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<string>("r_description")
                        .HasColumnType("longtext");

                    b.Property<string>("r_details_json")
                        .HasColumnType("json");

                    b.Property<long?>("r_duration_ms")
                        .HasColumnType("bigint");

                    b.Property<string>("r_endpoint")
                        .HasColumnType("longtext");

                    b.Property<string>("r_http_method")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("r_ip_address")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("r_status_code")
                        .HasColumnType("int");

                    b.Property<string>("r_type_action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.Property<string>("r_user_agent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("r_user_email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("r_user_id")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex("r_created_at");

                    b.HasIndex("r_type_action");

                    b.HasIndex("r_user_id");

                    b.HasIndex("r_user_id", "r_created_at");

                    b.ToTable("t_trace_action");
                });

            modelBuilder.Entity("print_attestation.Model.t_trace_connexion", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<DateTime>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<string>("r_details_json")
                        .HasColumnType("json");

                    b.Property<string>("r_email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("r_ip_address")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("r_raison_echec")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("r_session_token_hash")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("r_succes")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("r_token_expires_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("r_type_evenement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.Property<string>("r_user_agent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("r_user_id")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex("r_created_at");

                    b.HasIndex("r_email");

                    b.HasIndex("r_ip_address");

                    b.HasIndex("r_user_id");

                    b.HasIndex("r_succes", "r_created_at");

                    b.HasIndex("r_user_id", "r_created_at");

                    b.ToTable("t_trace_connexion");
                });

            modelBuilder.Entity("print_attestation.Model.t_user", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("r_date_last_statut")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("r_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("r_nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("r_password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("r_password_change_required")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("r_prenom")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("r_site_id_fk")
                        .HasColumnType("int");

                    b.Property<int>("r_statut")
                        .HasColumnType("int");

                    b.Property<string>("r_telephone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex("r_site_id_fk");

                    b.HasIndex(new[] { "r_email" }, "IX_User_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "r_telephone" }, "IX_User_Telephone");

                    b.ToTable("t_user");
                });

            modelBuilder.Entity("print_attestation.Model.t_user_role", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("r_role_id_fk")
                        .HasColumnType("int");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.Property<int>("r_user_id_fk")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex("r_role_id_fk");

                    b.HasIndex("r_user_id_fk");

                    b.ToTable("t_user_role");
                });

            modelBuilder.Entity("print_attestation.Model.t_demande_annulation", b =>
                {
                    b.HasOne("print_attestation.Model.t_motif_annulation", "r_motif_annulation")
                        .WithMany("r_users")
                        .HasForeignKey("r_motif_annulation_id_fk")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("print_attestation.Model.t_site", "r_site")
                        .WithMany()
                        .HasForeignKey("r_site_id_fk")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("print_attestation.Model.t_user", "r_user")
                        .WithMany()
                        .HasForeignKey("r_user_id_fk")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("r_motif_annulation");

                    b.Navigation("r_site");

                    b.Navigation("r_user");
                });

            modelBuilder.Entity("print_attestation.Model.t_job", b =>
                {
                    b.HasOne("print_attestation.Model.t_user", "r_user")
                        .WithMany("r_jobs")
                        .HasForeignKey("r_user_id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("r_user");
                });

            modelBuilder.Entity("print_attestation.Model.t_job_details", b =>
                {
                    b.HasOne("print_attestation.Model.t_job", "r_job")
                        .WithMany("r_job_details")
                        .HasForeignKey("r_job_id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("r_job");
                });

            modelBuilder.Entity("print_attestation.Model.t_refresh_token", b =>
                {
                    b.HasOne("print_attestation.Model.t_user", "r_user")
                        .WithMany("r_refresh_tokens")
                        .HasForeignKey("r_user_id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("r_user");
                });

            modelBuilder.Entity("print_attestation.Model.t_role_scope", b =>
                {
                    b.HasOne("print_attestation.Model.t_role", "r_role")
                        .WithMany("r_role_scopes")
                        .HasForeignKey("r_role_id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("print_attestation.Model.t_scope", "r_scope")
                        .WithMany("r_role_scopes")
                        .HasForeignKey("r_scope_code_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("r_role");

                    b.Navigation("r_scope");
                });

            modelBuilder.Entity("print_attestation.Model.t_session", b =>
                {
                    b.HasOne("print_attestation.Model.t_user", "r_user")
                        .WithMany("r_sessions")
                        .HasForeignKey("r_user_id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("r_user");
                });

            modelBuilder.Entity("print_attestation.Model.t_trace_action", b =>
                {
                    b.HasOne("print_attestation.Model.t_user", "r_user")
                        .WithMany()
                        .HasForeignKey("r_user_id");

                    b.Navigation("r_user");
                });

            modelBuilder.Entity("print_attestation.Model.t_trace_connexion", b =>
                {
                    b.HasOne("print_attestation.Model.t_user", "r_user")
                        .WithMany()
                        .HasForeignKey("r_user_id");

                    b.Navigation("r_user");
                });

            modelBuilder.Entity("print_attestation.Model.t_user", b =>
                {
                    b.HasOne("print_attestation.Model.t_site", "r_site")
                        .WithMany("r_users")
                        .HasForeignKey("r_site_id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("r_site");
                });

            modelBuilder.Entity("print_attestation.Model.t_user_role", b =>
                {
                    b.HasOne("print_attestation.Model.t_role", "r_role")
                        .WithMany("r_user_roles")
                        .HasForeignKey("r_role_id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("print_attestation.Model.t_user", "r_user")
                        .WithMany("r_user_roles")
                        .HasForeignKey("r_user_id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("r_role");

                    b.Navigation("r_user");
                });

            modelBuilder.Entity("print_attestation.Model.t_job", b =>
                {
                    b.Navigation("r_job_details");
                });

            modelBuilder.Entity("print_attestation.Model.t_motif_annulation", b =>
                {
                    b.Navigation("r_users");
                });

            modelBuilder.Entity("print_attestation.Model.t_role", b =>
                {
                    b.Navigation("r_role_scopes");

                    b.Navigation("r_user_roles");
                });

            modelBuilder.Entity("print_attestation.Model.t_scope", b =>
                {
                    b.Navigation("r_role_scopes");
                });

            modelBuilder.Entity("print_attestation.Model.t_site", b =>
                {
                    b.Navigation("r_users");
                });

            modelBuilder.Entity("print_attestation.Model.t_user", b =>
                {
                    b.Navigation("r_jobs");

                    b.Navigation("r_refresh_tokens");

                    b.Navigation("r_sessions");

                    b.Navigation("r_user_roles");
                });
#pragma warning restore 612, 618
        }
    }
}
