// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ask.ContextDb;

#nullable disable

namespace print_attestation.Migrations
{
    [DbContext(typeof(askContext))]
    [Migration("20260615123620__save_15.06.2026")]
    partial class _save_15062026
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ask.Model.t_histo_email", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<string>("r_bcc")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("r_body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("r_cc")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_html")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("r_raison_echec")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("r_recipients")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("r_sender_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("r_sender_name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("r_statut")
                        .HasColumnType("int");

                    b.Property<string>("r_subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex(new[] { "r_created_at" }, "IX_HistoEmail_CreatedAt");

                    b.HasIndex(new[] { "r_recipients" }, "IX_HistoEmail_Recipients");

                    b.HasIndex(new[] { "r_statut" }, "IX_HistoEmail_Statut");

                    b.ToTable("t_histo_email");
                });

            modelBuilder.Entity("ask.Model.t_histo_sms", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("r_provider_message_id")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("r_raison_echec")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("r_recipient")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("r_sender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("r_statut")
                        .HasColumnType("int");

                    b.Property<string>("r_text")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("varchar(1600)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex(new[] { "r_created_at" }, "IX_HistoSms_CreatedAt");

                    b.HasIndex(new[] { "r_recipient" }, "IX_HistoSms_Recipient");

                    b.HasIndex(new[] { "r_statut" }, "IX_HistoSms_Statut");

                    b.ToTable("t_histo_sms");
                });

            modelBuilder.Entity("ask.Model.t_modele", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<string>("r_body")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<string>("r_description")
                        .HasColumnType("longtext");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("r_plateforme")
                        .HasColumnType("int");

                    b.Property<string>("r_subject")
                        .HasColumnType("longtext");

                    b.Property<int?>("r_type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.ToTable("t_modele");
                });

            modelBuilder.Entity("ask.Model.t_refresh_token", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("r_expires_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("r_ip_address")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_revoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("r_jti")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("r_replaced_by")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("r_revoked_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("r_token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.Property<string>("r_user_agent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("r_user_id_fk")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex("r_expires_at", "r_is_delete")
                        .HasDatabaseName("IX_RefreshToken_ExpiresAt_IsDelete");

                    b.HasIndex("r_user_id_fk", "r_is_revoked", "r_expires_at")
                        .HasDatabaseName("IX_RefreshToken_UserId_IsRevoked_ExpiresAt");

                    b.HasIndex(new[] { "r_expires_at" }, "IX_RefreshToken_ExpiresAt");

                    b.HasIndex(new[] { "r_jti" }, "IX_RefreshToken_Jti");

                    b.HasIndex(new[] { "r_token" }, "IX_RefreshToken_Token")
                        .IsUnique();

                    b.HasIndex(new[] { "r_user_id_fk" }, "IX_RefreshToken_UserId");

                    b.ToTable("t_refresh_token");
                });

            modelBuilder.Entity("ask.Model.t_session", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<string>("r_ip_address")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("r_login_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("r_logout_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("r_token_jti")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.Property<string>("r_user_agent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("r_user_id_fk")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex("r_user_id_fk", "r_is_active", "r_login_at")
                        .HasDatabaseName("IX_Session_UserId_IsActive_LoginAt");

                    b.HasIndex(new[] { "r_is_active" }, "IX_Session_IsActive");

                    b.HasIndex(new[] { "r_login_at" }, "IX_Session_LoginAt");

                    b.HasIndex(new[] { "r_token_jti" }, "IX_Session_TokenJti");

                    b.HasIndex(new[] { "r_user_id_fk" }, "IX_Session_UserId");

                    b.ToTable("t_session");
                });

            modelBuilder.Entity("ask.Model.t_user", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<string>("r_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("r_failed_login_attempts")
                        .HasColumnType("int");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("r_last_login_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("r_locked_until")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("r_nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("r_password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("r_password_change_required")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("r_photo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("r_prenom")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("r_statut")
                        .HasColumnType("int");

                    b.Property<string>("r_telephone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("r_type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex(new[] { "r_email" }, "IX_User_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "r_telephone" }, "IX_User_Telephone");

                    b.ToTable("t_user");
                });

            modelBuilder.Entity("ask.Model.t_refresh_token", b =>
                {
                    b.HasOne("ask.Model.t_user", "r_userTab")
                        .WithMany("r_refresh_tokens")
                        .HasForeignKey("r_user_id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("r_userTab");
                });

            modelBuilder.Entity("ask.Model.t_session", b =>
                {
                    b.HasOne("ask.Model.t_user", "r_userTab")
                        .WithMany("r_sessions")
                        .HasForeignKey("r_user_id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("r_userTab");
                });

            modelBuilder.Entity("ask.Model.t_user", b =>
                {
                    b.Navigation("r_refresh_tokens");

                    b.Navigation("r_sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
