// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ask.ContextDb;

#nullable disable

namespace print_attestation.Migrations
{
    [DbContext(typeof(askContext))]
    [Migration("20260827105915__annn")]
    partial class _annn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ask.Model.t_demande_annulation", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("r_date_traitement")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("r_motif_annulation_id_fk")
                        .HasColumnType("int");

                    b.Property<string>("r_motif_rejet")
                        .HasColumnType("longtext");

                    b.Property<string>("r_num_attestation")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("r_num_immatriculation")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("r_num_police")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("r_site_id_fk")
                        .HasColumnType("int");

                    b.Property<int>("r_status")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.Property<int>("r_user_id_fk")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex("r_created_at");

                    b.HasIndex("r_motif_annulation_id_fk");

                    b.HasIndex("r_site_id_fk");

                    b.HasIndex("r_status");

                    b.HasIndex("r_user_id_fk");

                    b.ToTable("t_demande_annulation");
                });

            modelBuilder.Entity("ask.Model.t_histo_email", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<string>("r_bcc")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("r_body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("r_cc")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_html")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("r_raison_echec")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("r_recipients")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("r_sender_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("r_sender_name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("r_statut")
                        .HasColumnType("int");

                    b.Property<string>("r_subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex(new[] { "r_created_at" }, "IX_HistoEmail_CreatedAt");

                    b.HasIndex(new[] { "r_recipients" }, "IX_HistoEmail_Recipients");

                    b.HasIndex(new[] { "r_statut" }, "IX_HistoEmail_Statut");

                    b.ToTable("t_histo_email");
                });

            modelBuilder.Entity("ask.Model.t_histo_sms", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("r_provider_message_id")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("r_raison_echec")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("r_recipient")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("r_sender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("r_statut")
                        .HasColumnType("int");

                    b.Property<string>("r_text")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("varchar(1600)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex(new[] { "r_created_at" }, "IX_HistoSms_CreatedAt");

                    b.HasIndex(new[] { "r_recipient" }, "IX_HistoSms_Recipient");

                    b.HasIndex(new[] { "r_statut" }, "IX_HistoSms_Statut");

                    b.ToTable("t_histo_sms");
                });

            modelBuilder.Entity("ask.Model.t_job", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<string>("r_attestations")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("r_completed_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<int>("r_errors")
                        .HasColumnType("int");

                    b.Property<string>("r_file_name")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("r_file_path")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("r_job_id")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("r_status")
                        .HasColumnType("int");

                    b.Property<int>("r_success")
                        .HasColumnType("int");

                    b.Property<int>("r_total")
                        .HasColumnType("int");

                    b.Property<string>("r_type")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.Property<int>("r_user_id_fk")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex("r_created_at");

                    b.HasIndex("r_job_id");

                    b.HasIndex("r_user_id_fk");

                    b.HasIndex(new[] { "r_job_id" }, "IX_Job_JobId");

                    b.HasIndex(new[] { "r_user_id_fk" }, "IX_Job_UserId");

                    b.ToTable("t_job");
                });

            modelBuilder.Entity("ask.Model.t_job_details", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<string>("r_attestation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<string>("r_desc_error")
                        .HasColumnType("longtext");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("r_job_id_fk")
                        .HasColumnType("int");

                    b.Property<bool?>("r_success")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex("r_created_at");

                    b.HasIndex("r_job_id_fk");

                    b.HasIndex(new[] { "r_job_id_fk" }, "IX_Job_JobIdFk");

                    b.ToTable("t_job_details");
                });

            modelBuilder.Entity("ask.Model.t_modele", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<string>("r_body")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<string>("r_description")
                        .HasColumnType("longtext");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("r_plateforme")
                        .HasColumnType("int");

                    b.Property<string>("r_subject")
                        .HasColumnType("longtext");

                    b.Property<int?>("r_type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.ToTable("t_modele");
                });

            modelBuilder.Entity("ask.Model.t_motif_annulation", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("r_libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex("r_libelle");

                    b.ToTable("t_motif_annulation");
                });

            modelBuilder.Entity("ask.Model.t_refresh_token", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("r_expires_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("r_ip_address")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_revoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("r_jti")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("r_replaced_by")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("r_revoked_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("r_token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.Property<string>("r_user_agent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("r_user_id_fk")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex("r_expires_at", "r_is_delete")
                        .HasDatabaseName("IX_RefreshToken_ExpiresAt_IsDelete");

                    b.HasIndex("r_user_id_fk", "r_is_revoked", "r_expires_at")
                        .HasDatabaseName("IX_RefreshToken_UserId_IsRevoked_ExpiresAt");

                    b.HasIndex(new[] { "r_expires_at" }, "IX_RefreshToken_ExpiresAt");

                    b.HasIndex(new[] { "r_jti" }, "IX_RefreshToken_Jti");

                    b.HasIndex(new[] { "r_token" }, "IX_RefreshToken_Token")
                        .IsUnique();

                    b.HasIndex(new[] { "r_user_id_fk" }, "IX_RefreshToken_UserId");

                    b.ToTable("t_refresh_token");
                });

            modelBuilder.Entity("ask.Model.t_session", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<string>("r_ip_address")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("r_login_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("r_logout_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("r_token_jti")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.Property<string>("r_user_agent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("r_user_id_fk")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex("r_user_id_fk", "r_is_active", "r_login_at")
                        .HasDatabaseName("IX_Session_UserId_IsActive_LoginAt");

                    b.HasIndex(new[] { "r_is_active" }, "IX_Session_IsActive");

                    b.HasIndex(new[] { "r_login_at" }, "IX_Session_LoginAt");

                    b.HasIndex(new[] { "r_token_jti" }, "IX_Session_TokenJti");

                    b.HasIndex(new[] { "r_user_id_fk" }, "IX_Session_UserId");

                    b.ToTable("t_session");
                });

            modelBuilder.Entity("ask.Model.t_site", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<string>("r_code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("r_nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex(new[] { "r_code" }, "IX_Site_Code")
                        .IsUnique();

                    b.HasIndex(new[] { "r_nom" }, "IX_Site_Nom");

                    b.ToTable("t_site");
                });

            modelBuilder.Entity("ask.Model.t_trace_action", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<string>("r_description")
                        .HasColumnType("longtext");

                    b.Property<string>("r_details_json")
                        .HasColumnType("json");

                    b.Property<long?>("r_duration_ms")
                        .HasColumnType("bigint");

                    b.Property<string>("r_endpoint")
                        .HasColumnType("longtext");

                    b.Property<string>("r_http_method")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("r_ip_address")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("r_status_code")
                        .HasColumnType("int");

                    b.Property<string>("r_type_action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.Property<string>("r_user_agent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("r_user_email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("r_user_id")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex("r_created_at");

                    b.HasIndex("r_type_action");

                    b.HasIndex("r_user_id");

                    b.HasIndex("r_user_id", "r_created_at");

                    b.ToTable("t_trace_action");
                });

            modelBuilder.Entity("ask.Model.t_trace_connexion", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<DateTime>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<string>("r_details_json")
                        .HasColumnType("json");

                    b.Property<string>("r_email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("r_ip_address")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("r_raison_echec")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("r_session_token_hash")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("r_succes")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("r_token_expires_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("r_type_evenement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.Property<string>("r_user_agent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("r_user_id")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex("r_created_at");

                    b.HasIndex("r_email");

                    b.HasIndex("r_ip_address");

                    b.HasIndex("r_user_id");

                    b.HasIndex("r_succes", "r_created_at");

                    b.HasIndex("r_user_id", "r_created_at");

                    b.ToTable("t_trace_connexion");
                });

            modelBuilder.Entity("ask.Model.t_user", b =>
                {
                    b.Property<int>("r_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("r_id"));

                    b.Property<DateTime?>("r_created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_created_by")
                        .HasColumnType("int");

                    b.Property<DateTime?>("r_date_last_statut")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("r_email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("r_is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("r_is_delete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("r_nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("r_password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("r_password_change_required")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("r_prenom")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("r_site_id_fk")
                        .HasColumnType("int");

                    b.Property<int>("r_statut")
                        .HasColumnType("int");

                    b.Property<string>("r_telephone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("r_type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("r_updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("r_updated_by")
                        .HasColumnType("int");

                    b.HasKey("r_id");

                    b.HasIndex("r_site_id_fk");

                    b.HasIndex(new[] { "r_email" }, "IX_User_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "r_telephone" }, "IX_User_Telephone");

                    b.ToTable("t_user");
                });

            modelBuilder.Entity("ask.Model.t_demande_annulation", b =>
                {
                    b.HasOne("ask.Model.t_motif_annulation", "r_motif_annulation")
                        .WithMany("r_users")
                        .HasForeignKey("r_motif_annulation_id_fk")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ask.Model.t_site", "r_site")
                        .WithMany()
                        .HasForeignKey("r_site_id_fk")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ask.Model.t_user", "r_user")
                        .WithMany()
                        .HasForeignKey("r_user_id_fk")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("r_motif_annulation");

                    b.Navigation("r_site");

                    b.Navigation("r_user");
                });

            modelBuilder.Entity("ask.Model.t_job", b =>
                {
                    b.HasOne("ask.Model.t_user", "r_user")
                        .WithMany("r_jobs")
                        .HasForeignKey("r_user_id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("r_user");
                });

            modelBuilder.Entity("ask.Model.t_job_details", b =>
                {
                    b.HasOne("ask.Model.t_job", "r_job")
                        .WithMany("r_job_details")
                        .HasForeignKey("r_job_id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("r_job");
                });

            modelBuilder.Entity("ask.Model.t_refresh_token", b =>
                {
                    b.HasOne("ask.Model.t_user", "r_user")
                        .WithMany("r_refresh_tokens")
                        .HasForeignKey("r_user_id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("r_user");
                });

            modelBuilder.Entity("ask.Model.t_session", b =>
                {
                    b.HasOne("ask.Model.t_user", "r_user")
                        .WithMany("r_sessions")
                        .HasForeignKey("r_user_id_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("r_user");
                });

            modelBuilder.Entity("ask.Model.t_trace_action", b =>
                {
                    b.HasOne("ask.Model.t_user", "r_user")
                        .WithMany()
                        .HasForeignKey("r_user_id");

                    b.Navigation("r_user");
                });

            modelBuilder.Entity("ask.Model.t_trace_connexion", b =>
                {
                    b.HasOne("ask.Model.t_user", "r_user")
                        .WithMany()
                        .HasForeignKey("r_user_id");

                    b.Navigation("r_user");
                });

            modelBuilder.Entity("ask.Model.t_user", b =>
                {
                    b.HasOne("ask.Model.t_site", "r_site")
                        .WithMany("r_users")
                        .HasForeignKey("r_site_id_fk")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("r_site");
                });

            modelBuilder.Entity("ask.Model.t_job", b =>
                {
                    b.Navigation("r_job_details");
                });

            modelBuilder.Entity("ask.Model.t_motif_annulation", b =>
                {
                    b.Navigation("r_users");
                });

            modelBuilder.Entity("ask.Model.t_site", b =>
                {
                    b.Navigation("r_users");
                });

            modelBuilder.Entity("ask.Model.t_user", b =>
                {
                    b.Navigation("r_jobs");

                    b.Navigation("r_refresh_tokens");

                    b.Navigation("r_sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
