
public enum STATUT_EMAIL
{
    ATTENTE = 1,
    ENVOYE = 2,
    ECHOUE = 3
}

public enum STATUT_SMS
{
    ATTENTE = 1,
    ENVOYE = 2,
    ECHOUE = 3
}


public enum TYPE_UTILISATEUR
{
    ADMINISTRATEUR = 1,
    RESPONSABLE_RESEAU = 2,
    BUREAU_DIRECT = 3,
    RESPONSABLE_INTERMEDIAIRE = 4,
    UTILISATEUR = 5,
}

public enum TYPE_SITE
{
    SIEGE = 1,
    BUREAU_DIRECT = 2,
    BANCASSURANCE = 3,
    AGENT_GENERAL = 4,
    COURTTIER = 5,
    AUTRES = 6
}


public enum TYPE_JOB
{
    cedeao,
    atd
}

public enum STATUT_JOB
{
    RUNNING = 1,
    COMPLETED = 2,
    CANCELLED = 3,
    FAILED = 4
}


public enum STATUT_DEMANDE_ANNULATION
{
    EN_ATTENTE = 1,
    TRAITE = 2,
    REJETE = 3,
}



public enum PLATEFORME_MESSAGERIE
{
    SMS = 1,
    EMAIL = 2
}

public enum TYPE_MODELE
{
    REGISTER_SUCCESS = 1,
    RESET_PASSWORD = 2,
    COMPTE_DESACTIVE = 3,
    COMPTE_ACTIVE = 4,
    TELECHARGEMENT_EN_COURS = 5,
    TELECHARGEMENT_TERMINE = 6,
}



public enum STATUT_USER
{
    ACTIVE = 1,
    DESACTIVE = 2
}

/// <summary>
/// Types d'actions traçables dans le système
/// </summary>
public enum TYPE_ACTION
{
    // Authentification
    CONNEXION_REUSSIE,
    CONNEXION_ECHOUEE,
    DECONNEXION,
    RAFRAICHISSEMENT_TOKEN,

    // Utilisateurs
    CREATION_UTILISATEUR,
    MODIFICATION_UTILISATEUR,
    SUPPRESSION_UTILISATEUR,
    ACTIVATION_UTILISATEUR,
    DESACTIVATION_UTILISATEUR,
    REINITIALISATION_MOT_DE_PASSE,
    MODIFICATION_MOT_DE_PASSE,

    // Attestations
    RECHERCHE_ATTESTATION,
    TELECHARGEMENT_ATD,
    TELECHARGEMENT_CEDEAO,
    TELECHARGEMENT_ZIP,
    EXPORT_CEDEAO_ZIP,
    EXPORT_ATD_ZIP,
    GENERATION_CEDEAO_ZIP,
    GENERATION_ATD_ZIP,
    GENERATION_ATD_CEDEAO_ZIP,
    ANNULATION_GENERATION_ZIP,
    // Modèles
    CONSULTATION_MODELE,
    MODIFICATION_MODELE,
    CREATION_MODELE,
    SUPPRESSION_MODELE,

    // Création site
    CONSULTATION_SITE,
    MODIFICATION_SITE,
    CREATION_SITE,
    SUPPRESSION_SITE,


    // Création role
    CONSULTATION_ROLE,
    MODIFICATION_ROLE,
    CREATION_ROLE,
    SUPPRESSION_ROLE,



    // Création motif d'annulation
    CONSULTATION_MOTIF_ANNULATION,
    MODIFICATION_MOTIF_ANNULATION,
    CREATION_MOTIF_ANNULATION,
    SUPPRESSION_MOTIF_ANNULATION,

    // Administration
    CONSULTATION_LISTE_UTILISATEURS,
    CREER_UTILISATEUR,
    MODIFIER_UTILISATEUR,
    ACTIVER_UTILISATEUR,
    DESACTIVER_UTILISATEUR,
    REINITIALISATION_UTILISATEUR,
    CONSULTATION_LOGS,

    // Autres
    ERREUR_SYSTEME,
    ACCES_REFUSE,
    REQUETE_INVALIDE
}

/// <summary>
/// Types d'événements de connectivité
/// </summary>
public enum TYPE_CONNEXION
{
    // Connexions
    CONNEXION_REUSSIE,
    CONNEXION_ECHOUEE_MOT_DE_PASSE,
    CONNEXION_ECHOUEE_COMPTE_INEXISTANT,
    CONNEXION_ECHOUEE_COMPTE_DESACTIVE,
    CONNEXION_ECHOUEE_BLOQUE,

    // Déconnexions
    DECONNEXION_NORMALE,
    DECONNEXION_EXPIRATION_TOKEN,
    DECONNEXION_FORCEE,
    DECONNEXION_AUTOMATIQUE,

    // Tokens
    RAFRAICHISSEMENT_TOKEN_REUSSI,
    RAFRAICHISSEMENT_TOKEN_ECHOUE,
    TOKEN_INVALIDE,
    TOKEN_EXPIRE,

    // Sécurité
    TENTATIVE_ACCES_NON_AUTORISE,
    IP_BLOQUEE,
    TROP_DE_TENTATIVES,
    CHANGEMENT_IP_DETECTE,

    // Sessions
    SESSION_CREEE,
    SESSION_TERMINEE,
    SESSION_EXPIREE
}
